"""Add auth app status and icon

Revision ID: 080056f84b2c
Revises: 0415fa899a86
Create Date: 2015-12-30 21:22:32.502232

"""

# revision identifiers, used by Alembic.
revision = '080056f84b2c'
down_revision = '0415fa899a86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_auth_apps', sa.Column('app_icon', sa.Text(), nullable=True))
    op.add_column('wr_auth_apps', sa.Column('app_status', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wr_auth_apps', 'app_status')
    op.drop_column('wr_auth_apps', 'app_icon')
    ### end Alembic commands ###
