"""fix

Revision ID: 1a2dd228e2b2
Revises: 080056f84b2c
Create Date: 2015-12-30 21:27:23.219936

"""

# revision identifiers, used by Alembic.
revision = '1a2dd228e2b2'
down_revision = '080056f84b2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_auth_apps', sa.Column('app_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wr_auth_apps', 'app_status')
    ### end Alembic commands ###
