"""Add access_token

Revision ID: 2549d9d3ce80
Revises: 1a2dd228e2b2
Create Date: 2016-01-05 20:57:23.317132

"""

# revision identifiers, used by Alembic.
revision = '2549d9d3ce80'
down_revision = '1a2dd228e2b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_auth_apps', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('wr_auth_apps', sa.Column('token_expire', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wr_auth_apps', 'token_expire')
    op.drop_column('wr_auth_apps', 'access_token')
    ### end Alembic commands ###
