"""fix#2

Revision ID: 49c32eeee323
Revises: 8ca3928ef055
Create Date: 2016-01-16 21:18:11.522278

"""

# revision identifiers, used by Alembic.
revision = '49c32eeee323'
down_revision = '8ca3928ef055'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wr_videos_video_score'), 'wr_videos', ['video_score'], unique=False)
    op.create_index(op.f('ix_wr_videos_video_star_count'), 'wr_videos', ['video_star_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wr_videos_video_star_count'), table_name='wr_videos')
    op.drop_index(op.f('ix_wr_videos_video_score'), table_name='wr_videos')
    ### end Alembic commands ###
