"""Add star count for video

Revision ID: 63cb00d5fde5
Revises: 8e74a4947c4c
Create Date: 2016-01-16 21:01:26.590859

"""

# revision identifiers, used by Alembic.
revision = '63cb00d5fde5'
down_revision = '8e74a4947c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_videos', sa.Column('video_star_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_wr_videos_video_score'), 'wr_videos', ['video_score'], unique=False)
    op.create_index(op.f('ix_wr_videos_video_star_count'), 'wr_videos', ['video_star_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wr_videos_video_star_count'), table_name='wr_videos')
    op.drop_index(op.f('ix_wr_videos_video_score'), table_name='wr_videos')
    op.drop_column('wr_videos', 'video_star_count')
    ### end Alembic commands ###
