"""fix#1

Revision ID: 8ca3928ef055
Revises: 63cb00d5fde5
Create Date: 2016-01-16 21:12:50.229331

"""

# revision identifiers, used by Alembic.
revision = '8ca3928ef055'
down_revision = '63cb00d5fde5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_videos', sa.Column('video_star_count', sa.Integer(), nullable=True))
    op.alter_column('wr_videos', 'video_play_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wr_videos', 'video_score',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_wr_videos_video_score'), 'wr_videos', ['video_score'], unique=False)
    op.create_index(op.f('ix_wr_videos_video_star_count'), 'wr_videos', ['video_star_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wr_videos_video_star_count'), table_name='wr_videos')
    op.drop_index(op.f('ix_wr_videos_video_score'), table_name='wr_videos')
    op.alter_column('wr_videos', 'video_score',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('wr_videos', 'video_play_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('wr_videos', 'video_star_count')
    ### end Alembic commands ###
