"""Add openid to User table

Revision ID: 8e74a4947c4c
Revises: 2ae8c888bb30
Create Date: 2016-01-10 23:32:13.342502

"""

# revision identifiers, used by Alembic.
revision = '8e74a4947c4c'
down_revision = '2ae8c888bb30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wr_users', sa.Column('open_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wr_users', 'open_id')
    ### end Alembic commands ###
