"""Add authapp table

Revision ID: a1135db7a8e7
Revises: 30850ceb202d
Create Date: 2015-12-28 17:37:15.763671

"""

# revision identifiers, used by Alembic.
revision = 'a1135db7a8e7'
down_revision = '30850ceb202d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wr_auth_apps',
    sa.Column('app_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('app_key', sa.String(length=32), nullable=False),
    sa.Column('app_secret', sa.String(length=32), nullable=False),
    sa.Column('app_url', sa.Text(), nullable=False),
    sa.Column('app_name', sa.String(length=32), nullable=False),
    sa.Column('app_created', sa.DateTime(), nullable=False),
    sa.Column('app_request_count', sa.Integer(), nullable=False),
    sa.Column('app_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['wr_users.user_ID'], ),
    sa.PrimaryKeyConstraint('app_ID'),
    sa.UniqueConstraint('app_key'),
    sa.UniqueConstraint('app_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wr_auth_apps')
    ### end Alembic commands ###
