"""video score to 100 format

Revision ID: ae5da51b63b0
Revises: 49c32eeee323
Create Date: 2016-01-16 22:12:49.525914

"""

# revision identifiers, used by Alembic.
revision = 'ae5da51b63b0'
down_revision = '49c32eeee323'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
